name: nf-villumina-2.0.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - curl=7.64.1
  - fastp=0.20.0
  - fastqc=0.11.9
  - bbmap=38.75
  - multiqc=1.8
  - centrifuge=1.0.4_beta
  - kraken2=2.0.8_beta
  - unicycler=0.4.8
  - shovill=1.0.9
  - samtools=1.10
  - python=3.6.7
  - seqtk
  - pbgzip
  - pip:
    - filter_classified_reads=0.2.0
    - attrs
    - numpy
    - pandas
